import Foundation

// Ported from client/src/pages/calendar.tsx EVENTS array (130+ entries)

enum CalendarEvents {
    private static let df: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd"
        f.timeZone = TimeZone(identifier: "Asia/Kolkata")
        return f
    }()

    private static func d(_ s: String) -> Date {
        df.date(from: s) ?? Date()
    }

    static let all: [CalendarEvent] = usda + mpob + policy + advisory + harvest + trade

    // MARK: - USDA WASDE Monthly Reports

    static let usda: [CalendarEvent] = [
        CalendarEvent(id: "w1",  title: "USDA WASDE Report — January",    date: d("2026-01-09"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "World Agricultural Supply and Demand Estimates. Key data on global wheat, rice, coarse grains, oilseeds, and cotton.", source: "USDA"),
        CalendarEvent(id: "w2",  title: "USDA WASDE Report — February",   date: d("2026-02-11"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "Updated supply/demand outlook for all major crops including soybean, palm oil, and sugar.", source: "USDA"),
        CalendarEvent(id: "w3",  title: "USDA WASDE Report — March",      date: d("2026-03-11"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "Mid-season update. Crop year balances for India, Brazil and Argentina closely watched.", source: "USDA"),
        CalendarEvent(id: "w4",  title: "USDA WASDE Report — April",      date: d("2026-04-09"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "Southern hemisphere harvest revisions. India wheat crop estimate typically revised here.", source: "USDA"),
        CalendarEvent(id: "w5",  title: "USDA WASDE Report — May",        date: d("2026-05-12"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "First projections for new crop year (2026-27). Monsoon impact on Kharif acreage discussed.", source: "USDA"),
        CalendarEvent(id: "w6",  title: "USDA WASDE Report — June",       date: d("2026-06-11"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "New-crop outlook with early Kharif sowing data from India; US corn/soy crop condition.", source: "USDA"),
        CalendarEvent(id: "w7",  title: "USDA WASDE Report — July",       date: d("2026-07-09"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "Mid-season monsoon impact assessment for India Kharif. Brazilian safrinha soy harvest.", source: "USDA"),
        CalendarEvent(id: "w8",  title: "USDA WASDE Report — August",     date: d("2026-08-12"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "US crop production estimates and India Kharif acreage finalization.", source: "USDA"),
        CalendarEvent(id: "w9",  title: "USDA WASDE Report — September",  date: d("2026-09-11"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "Pre-harvest estimates for India Kharif crops. Palm oil supply tightness window.", source: "USDA"),
        CalendarEvent(id: "w10", title: "USDA WASDE Report — October",    date: d("2026-10-09"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "India Kharif harvest data; Rabi sowing outlook. Southern hemisphere new-crop projections.", source: "USDA"),
        CalendarEvent(id: "w11", title: "USDA WASDE Report — November",   date: d("2026-11-12"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "Updated global sugar, wheat and rice balances. Argentina new-crop soybean.", source: "USDA"),
        CalendarEvent(id: "w12", title: "USDA WASDE Report — December",   date: d("2026-12-10"), startDate: nil, endDate: nil, category: .report, commodity: nil,        description: "Year-end crop estimates. India Rabi sowing progress update.", source: "USDA"),
    ]

    // MARK: - MPOB Monthly Palm Oil Reports

    static let mpob: [CalendarEvent] = [
        CalendarEvent(id: "m1",  title: "MPOB Palm Oil Data — January",   date: d("2026-01-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Malaysian Palm Oil Board monthly production, export, and stock data. Key price driver.", source: "MPOB"),
        CalendarEvent(id: "m2",  title: "MPOB Palm Oil Data — February",  date: d("2026-02-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Monthly CPO output and inventory report from Malaysia.", source: "MPOB"),
        CalendarEvent(id: "m3",  title: "MPOB Palm Oil Data — March",     date: d("2026-03-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Off-season production trough; stock levels closely monitored.", source: "MPOB"),
        CalendarEvent(id: "m4",  title: "MPOB Palm Oil Data — April",     date: d("2026-04-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Seasonal production recovery begins. Indonesia GAPKI data also released.", source: "MPOB"),
        CalendarEvent(id: "m5",  title: "MPOB Palm Oil Data — May",       date: d("2026-05-11"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Pre-peak season inventory build.", source: "MPOB"),
        CalendarEvent(id: "m6",  title: "MPOB Palm Oil Data — June",      date: d("2026-06-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Eid export demand window assessed.", source: "MPOB"),
        CalendarEvent(id: "m7",  title: "MPOB Palm Oil Data — July",      date: d("2026-07-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Peak production season begins; Bursa Malaysia contracts closely watched.", source: "MPOB"),
        CalendarEvent(id: "m8",  title: "MPOB Palm Oil Data — August",    date: d("2026-08-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Indonesia biodiesel mandate impact on export volumes.", source: "MPOB"),
        CalendarEvent(id: "m9",  title: "MPOB Palm Oil Data — September", date: d("2026-09-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Peak season output. Stock build or drawdown — critical for CPO prices.", source: "MPOB"),
        CalendarEvent(id: "m10", title: "MPOB Palm Oil Data — October",   date: d("2026-10-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Production peak window. Global edible oil demand shifts.", source: "MPOB"),
        CalendarEvent(id: "m11", title: "MPOB Palm Oil Data — November",  date: d("2026-11-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Post-peak production decline; festive demand impact.", source: "MPOB"),
        CalendarEvent(id: "m12", title: "MPOB Palm Oil Data — December",  date: d("2026-12-10"), startDate: nil, endDate: nil, category: .report, commodity: "Palm Oil", description: "Year-end stock levels set the tone for Q1 2027.", source: "MPOB"),
    ]

    // MARK: - India Policy Events

    static let policy: [CalendarEvent] = [
        CalendarEvent(id: "p1",  title: "Union Budget 2026-27",             date: d("2026-02-01"), startDate: nil, endDate: nil, category: .policy, commodity: nil,       description: "Annual Union Budget — import duties, MSP allocations, agri credit targets, and APMC reforms announced. Critical for all commodity prices.", source: "MoF India"),
        CalendarEvent(id: "p2",  title: "Kharif MSP Announcement",          date: d("2026-06-18"), startDate: nil, endDate: nil, category: .policy, commodity: "Multiple", description: "Cabinet Committee on Economic Affairs approves Minimum Support Prices for Kharif crops (Paddy, Maize, Chana, Cotton, Soybean, Groundnut, Sugarcane). Impacts farm economics across India.", source: "CACP India"),
        CalendarEvent(id: "p3",  title: "Rabi MSP Announcement",            date: d("2026-10-20"), startDate: nil, endDate: nil, category: .policy, commodity: "Wheat",   description: "MSP fixation for Rabi crops (Wheat, Gram, Mustard, Lentil). Key signal for procurement operations by FCI and state agencies.", source: "CACP India"),
        CalendarEvent(id: "p4",  title: "FCI Wheat Procurement Opens",      date: d("2026-04-01"), startDate: nil, endDate: nil, category: .policy, commodity: "Wheat",   description: "Food Corporation of India opens Rabi wheat procurement in Punjab, Haryana, MP and UP. Procurement quantities influence open-market prices.", source: "FCI India"),
        CalendarEvent(id: "p5",  title: "DGFT Export-Import Policy Review",date: d("2026-01-15"), startDate: nil, endDate: nil, category: .policy, commodity: nil,       description: "Quarterly review of export incentives, duty drawback rates, and advance authorisation norms. Key for cashew, spice, and rice exporters.", source: "DGFT"),
        CalendarEvent(id: "p6",  title: "DGFT Export-Import Policy Review",date: d("2026-04-15"), startDate: nil, endDate: nil, category: .policy, commodity: nil,       description: "Mid-year export-import policy review. Any changes to export bans, MEPs or duty concessions typically notified here.", source: "DGFT"),
        CalendarEvent(id: "p7",  title: "DGFT Export-Import Policy Review",date: d("2026-07-15"), startDate: nil, endDate: nil, category: .policy, commodity: nil,       description: "Post-budget policy alignment; trade facilitation measures reviewed.", source: "DGFT"),
        CalendarEvent(id: "p8",  title: "DGFT Export-Import Policy Review",date: d("2026-10-15"), startDate: nil, endDate: nil, category: .policy, commodity: nil,       description: "Pre-winter export window review. Key for onion, wheat, and pulses.", source: "DGFT"),
        CalendarEvent(id: "p9",  title: "Sugar Crushing Season Ends",       date: d("2026-03-31"), startDate: nil, endDate: nil, category: .policy, commodity: "Sugar",   description: "North Indian sugar mills typically complete the crushing season. ISMA final production estimates released. Impacts sugar and ethanol blending targets.", source: "ISMA"),
        CalendarEvent(id: "p10", title: "Sugar Crushing Season Begins",     date: d("2026-10-01"), startDate: nil, endDate: nil, category: .policy, commodity: "Sugar",   description: "New crushing season 2026-27 commences across Maharashtra, UP and Karnataka. ISMA advance estimate closely tracked.", source: "ISMA"),
        CalendarEvent(id: "p11", title: "FCI Wheat Procurement Closes",     date: d("2026-05-01"), startDate: nil, endDate: nil, category: .policy, commodity: "Wheat",   description: "Rabi wheat procurement concludes. Final procurement numbers vs. targets shape market supply expectations.", source: "FCI"),
    ]

    // MARK: - IMD / Weather Advisories

    static let advisory: [CalendarEvent] = [
        CalendarEvent(id: "a1", title: "IMD Pre-Monsoon Crop Advisory",    date: d("2026-04-15"), startDate: nil, endDate: nil, category: .advisory, commodity: nil, description: "India Meteorological Department releases the April crop advisory with heat stress warnings and pre-sowing guidance for Kharif crops.", source: "IMD"),
        CalendarEvent(id: "a2", title: "IMD Southwest Monsoon Forecast",   date: d("2026-04-30"), startDate: nil, endDate: nil, category: .advisory, commodity: nil, description: "IMD Long-Range Forecast (LRF) for Southwest Monsoon 2026. Quantitative normal/below-normal/above-normal forecast. Markets react strongly to this data.", source: "IMD"),
        CalendarEvent(id: "a3", title: "Monsoon Onset — Kerala (Expected)",date: d("2026-06-01"), startDate: nil, endDate: nil, category: .advisory, commodity: nil, description: "Normal date for Southwest Monsoon onset over Kerala. Actual onset ±1 week triggers Kharif sowing adjustments across India.", source: "IMD"),
        CalendarEvent(id: "a4", title: "IMD Monsoon Progress Update",      date: d("2026-06-15"), startDate: nil, endDate: nil, category: .advisory, commodity: nil, description: "IMD 2nd updated Long-Range Forecast for monsoon. Spatial distribution across agri zones assessed.", source: "IMD"),
        CalendarEvent(id: "a5", title: "IMD Monsoon Withdrawal Begins",    date: d("2026-09-01"), startDate: nil, endDate: nil, category: .advisory, commodity: nil, description: "Southwest Monsoon withdrawal typically begins from Rajasthan. Impacts late Kharif crops and early Rabi sowing window.", source: "IMD"),
        CalendarEvent(id: "a6", title: "Northeast Monsoon Onset",          date: d("2026-10-15"), startDate: nil, endDate: nil, category: .advisory, commodity: nil, description: "NE Monsoon onset over Tamil Nadu. Critical for irrigated rice in south India and post-kharif crops.", source: "IMD"),
        CalendarEvent(id: "a7", title: "ENSO / El Niño Status Update",     date: d("2026-05-15"), startDate: nil, endDate: nil, category: .advisory, commodity: nil, description: "IMD & NOAA joint update on El Niño/La Niña conditions. Influences Indian monsoon intensity and global grain production.", source: "IMD/NOAA"),
        CalendarEvent(id: "a8", title: "IMD Rabi Crop Advisory",           date: d("2026-11-15"), startDate: nil, endDate: nil, category: .advisory, commodity: nil, description: "Winter crop advisory covering cold wave risks, fog impact on wheat, and moisture adequacy for rabi crop development.", source: "IMD/ICAR"),
        CalendarEvent(id: "a9", title: "ICAR Kharif Variety Advisories",   date: d("2026-03-15"), startDate: nil, endDate: nil, category: .advisory, commodity: nil, description: "ICAR releases recommended high-yield variety bulletins for Kharif 2026. Farmers and traders watch for acreage shift signals.", source: "ICAR"),
    ]

    // MARK: - Harvest Seasons (Ranges)

    static let harvest: [CalendarEvent] = [
        CalendarEvent(id: "hs1",  title: "Rabi Harvest Season",             date: nil, startDate: d("2026-03-01"), endDate: d("2026-05-15"), category: .harvest, commodity: "Wheat / Chana",              description: "India Rabi harvest in progress — wheat, chickpea (chana), mustard, and lentils. Bulk arrivals depress mandi prices; FCI procurement absorbs supply.", source: nil),
        CalendarEvent(id: "hs2",  title: "Cashew Harvest — India",          date: nil, startDate: d("2026-03-01"), endDate: d("2026-06-15"), category: .harvest, commodity: "Cashew",                     description: "Coastal cashew harvest season in Goa, Kerala, Karnataka, and Maharashtra. Fresh Raw Cashew Nut (RCN) arrivals from West Africa (Ivory Coast, Guinea-Bissau) begin April onward.", source: nil),
        CalendarEvent(id: "hs3",  title: "Mango Season — India",            date: nil, startDate: d("2026-04-01"), endDate: d("2026-06-30"), category: .harvest, commodity: "Mango",                      description: "Alphonso, Kesar, Dasheri and Langra mango season. Drives packaging demand for corrugated boxes and cold-chain logistics.", source: nil),
        CalendarEvent(id: "hs4",  title: "Onion (Rabi) Harvest",            date: nil, startDate: d("2026-03-01"), endDate: d("2026-05-15"), category: .harvest, commodity: "Onion",                      description: "Maharashtra Rabi onion harvest — largest supply event of the year. Price softening typical in April-May. NAFED/NCCF buffer stock operations.", source: nil),
        CalendarEvent(id: "hs5",  title: "Kharif Sowing Season",            date: nil, startDate: d("2026-06-01"), endDate: d("2026-07-31"), category: .harvest, commodity: "Paddy / Soybean / Cotton",   description: "India Kharif sowing begins after monsoon onset. Key crops: Paddy, Soybean, Cotton, Groundnut, Maize. Acreage reports released weekly by Dept. of Agriculture.", source: nil),
        CalendarEvent(id: "hs6",  title: "Almond Harvest — California",     date: nil, startDate: d("2026-08-01"), endDate: d("2026-10-15"), category: .harvest, commodity: "Almond",                     description: "US almond harvest window. California accounts for ~80% of global almond supply. ABC crop estimate in May sets tone; harvest confirms final yields.", source: nil),
        CalendarEvent(id: "hs7",  title: "Palm Oil Peak Production",        date: nil, startDate: d("2026-08-01"), endDate: d("2026-10-31"), category: .harvest, commodity: "Palm Oil",                   description: "Malaysia and Indonesia peak palm oil production window. CPO output highest July-October. Stock build and export pace determine price direction on Bursa Malaysia.", source: nil),
        CalendarEvent(id: "hs8",  title: "Cotton Harvest — India",          date: nil, startDate: d("2026-09-01"), endDate: d("2026-12-15"), category: .harvest, commodity: "Cotton",                     description: "Gujarat, Maharashtra, and Telangana cotton (kapas) harvest. CCI procurement under MSP scheme. Cottonseed oil output linked to this season.", source: nil),
        CalendarEvent(id: "hs9",  title: "Kharif Harvest Season",           date: nil, startDate: d("2026-10-01"), endDate: d("2026-11-30"), category: .harvest, commodity: "Paddy / Soybean / Groundnut", description: "Major Kharif crop arrivals — Paddy, Soybean, Groundnut, Maize. Soybean crushing margins and CPO import substitution demand in focus.", source: nil),
        CalendarEvent(id: "hs10", title: "Rabi Sowing Season",              date: nil, startDate: d("2026-10-15"), endDate: d("2026-12-15"), category: .harvest, commodity: "Wheat / Chana",              description: "Rabi crops sown across India. Wheat in Punjab, Haryana, UP, MP; Chana/Chickpea in MP and Rajasthan. Soil moisture from retreating monsoon is critical.", source: nil),
        CalendarEvent(id: "hs11", title: "Cocoa Main Crop — West Africa",   date: nil, startDate: d("2026-10-01"), endDate: d("2026-12-31"), category: .harvest, commodity: "Cocoa",                      description: "Ivory Coast and Ghana main crop harvest (Oct–Mar). Quality assessment, arrivals, and farmer payments set the global cocoa price trajectory.", source: nil),
        CalendarEvent(id: "hs12", title: "Cardamom Harvest — Kerala",       date: nil, startDate: d("2026-07-01"), endDate: d("2026-11-30"), category: .harvest, commodity: "Cardamom",                   description: "Green cardamom harvest in Idukki and Wayanad districts. Spices Board e-auction prices monitored by exporters and traders.", source: nil),
        CalendarEvent(id: "hs13", title: "Black Pepper Harvest — Kerala",   date: nil, startDate: d("2026-12-01"), endDate: d("2026-12-31"), category: .harvest, commodity: "Black Pepper",               description: "Berry black pepper harvest begins in December in Wayanad, Kozhikode and Kannur. Vietnam season ends; India's share supports global prices.", source: nil),
        CalendarEvent(id: "hs14", title: "Turmeric Harvest",                date: nil, startDate: d("2026-01-01"), endDate: d("2026-03-31"), category: .harvest, commodity: "Turmeric",                   description: "Sangli and Nizamabad turmeric harvest season. Curcumin content highest in this window. Export demand from US, Europe, and Middle East tracked.", source: nil),
        CalendarEvent(id: "hs15", title: "Raisins Harvest — Sangli/Nashik", date: nil, startDate: d("2026-09-01"), endDate: d("2026-11-30"), category: .harvest, commodity: "Raisins",                    description: "Maharashtra grapevine harvest and raisin drying season. Sangli is Asia's largest raisin market. Export parity critical vs. Afghan/Turkish raisins.", source: nil),
        CalendarEvent(id: "hs16", title: "Kharif Groundnut Sowing",         date: nil, startDate: d("2026-04-01"), endDate: d("2026-06-30"), category: .harvest, commodity: "Groundnut",                  description: "Gujarat and Andhra Pradesh groundnut sowing under Kharif. NAFED procurement under MSP critical. Groundnut oil presses begin monitoring new-crop arrivals from October.", source: nil),
        CalendarEvent(id: "hs17", title: "Isabgol (Psyllium) Harvest",      date: nil, startDate: d("2026-02-15"), endDate: d("2026-04-30"), category: .harvest, commodity: "Psyllium",                   description: "Rajasthan isabgol (psyllium husk) harvest. India supplies ~90% of global psyllium. DMRP and ACS assessments released by Gujarat Agri Dept.", source: nil),
    ]

    // MARK: - Market / Trade Events

    static let trade: [CalendarEvent] = [
        CalendarEvent(id: "t1",  title: "APEDA Monthly Export Data — Jan",  date: d("2026-01-20"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "Agricultural & Processed Food Products Export Development Authority releases monthly export figures for rice, spices, cashew, and fresh produce.", source: "APEDA"),
        CalendarEvent(id: "t2",  title: "APEDA Monthly Export Data — Feb",  date: d("2026-02-20"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "February Agri export data. Rice exports most closely watched; Non-basmati and basmati volumes vs. previous year.", source: "APEDA"),
        CalendarEvent(id: "t3",  title: "APEDA Monthly Export Data — Mar",  date: d("2026-03-20"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "Pre-new crop year export data. Spices, cashew, and fresh mango shipment data.", source: "APEDA"),
        CalendarEvent(id: "t4",  title: "APEDA Monthly Export Data — Apr",  date: d("2026-04-20"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "Mango export season begins. Alphonso US-UAE shipments tracked.", source: "APEDA"),
        CalendarEvent(id: "t5",  title: "APEDA Monthly Export Data — May",  date: d("2026-05-20"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "Cashew kernel export peak window. May APEDA data critical for Vietnam vs. India market share.", source: "APEDA"),
        CalendarEvent(id: "t6",  title: "APEDA Monthly Export Data — Jun",  date: d("2026-06-20"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "Year-end export performance data. FY totals for rice, spices, and pulses.", source: "APEDA"),
        CalendarEvent(id: "t7",  title: "NCDEX Futures Expiry — March",     date: d("2026-03-31"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "NCDEX commodity futures March contract expiry — Chana, Soybean, Castor, Coriander, Jeera contracts. Rollover activity impacts near-term prices.", source: "NCDEX"),
        CalendarEvent(id: "t8",  title: "NCDEX Futures Expiry — June",      date: d("2026-06-30"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "June contract expiry. Monsoon progress impacts Kharif-linked futures rollover.", source: "NCDEX"),
        CalendarEvent(id: "t9",  title: "NCDEX Futures Expiry — September", date: d("2026-09-30"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "Pre-harvest futures expiry. New-crop Soybean and Chana contracts take centre stage.", source: "NCDEX"),
        CalendarEvent(id: "t10", title: "NCDEX Futures Expiry — December",  date: d("2026-12-31"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "Year-end futures contract expiry. Rabi crop sowing progress sets tone for Jan contracts.", source: "NCDEX"),
        CalendarEvent(id: "t11", title: "Anuga FoodTec — Cologne",          date: d("2026-03-15"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "Global food technology and packaging exhibition. Key networking event for flexible packaging, laminates, and BOPP/BOPET film manufacturers.", source: "Koelnmesse"),
        CalendarEvent(id: "t12", title: "World Food India",                 date: d("2026-11-05"), startDate: nil, endDate: nil, category: .trade, commodity: nil,       description: "India's flagship food processing industry event. Government announces export targets, PLI scheme updates, and APEDA partnerships.", source: "DPIIT"),
        CalendarEvent(id: "t13", title: "Soyabean Crop Tour — India",       date: d("2026-09-15"), startDate: nil, endDate: nil, category: .trade, commodity: "Soyabean", description: "Soybean Processors Association of India (SOPA) field crop tour in Madhya Pradesh. Production estimate closely tracked by oil mills and importers.", source: "SOPA"),
        CalendarEvent(id: "t14", title: "Vietnam Cashew Export Report — Q4",date: d("2026-01-16"), startDate: nil, endDate: nil, category: .trade, commodity: "Cashew",  description: "Vietnam Cashew Association quarterly export report. Vietnam is world's largest cashew exporter; India vs. Vietnam price competition drives kernel markets.", source: "VINACAS"),
        CalendarEvent(id: "t15", title: "Vietnam Cashew Export Report — H1",date: d("2026-07-16"), startDate: nil, endDate: nil, category: .trade, commodity: "Cashew",  description: "Mid-year cashew export volumes from Vietnam. India's RCN processing margins vs. direct kernel imports evaluated.", source: "VINACAS"),
    ]
}
